//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4253
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace logMente.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("logMente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;searchConditions&gt;
        ///  &lt;searchCondition&gt;
        ///    &lt;checked&gt;True&lt;/checked&gt;
        ///    &lt;name&gt;テスト条件True&lt;/name&gt;
        ///    &lt;value&gt;TEST CONDITION True&lt;/value&gt;
        ///    &lt;index&gt;12&lt;/index&gt;
        ///  &lt;/searchCondition&gt;
        ///
        ///  &lt;searchCondition&gt;
        ///    &lt;checked&gt;3&lt;/checked&gt;
        ///    &lt;name&gt;テスト条件3&lt;/name&gt;
        ///    &lt;value&gt;TEST CONDITION 3&lt;/value&gt;
        ///    &lt;index&gt;2&lt;/index&gt;
        ///  &lt;/searchCondition&gt;
        ///
        ///  &lt;searchCondition&gt;
        ///    &lt;checked&gt;10&lt;/checked&gt;
        ///    &lt;name&gt;テスト条件10&lt;/name&gt;
        ///    &lt;value&gt;TEST CONDITION 10&lt;/value&gt;
        ///    &lt;index&gt;5&lt;/index&gt;
        ///  &lt;/searchCondition&gt;
        ///  &lt;searchConditi [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string saveCondition {
            get {
                return ResourceManager.GetString("saveCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;xsl:stylesheet xmlns:xsl=”http://www.w3.org/1999/XSL/Transform” version=”1.0″&gt;
        ///&lt;xsl:template match=”NewDataSet”&gt;
        ///&lt;xsl:apply-templates select=”Table” /&gt;
        ///&lt;/xsl:template&gt;
        ///&lt;xsl:template match=”Table”&gt;
        ///&lt;xsl:value-of select=”Column_A” /&gt;,&lt;xsl:value-of select=”Column_B” /&gt;,&lt;xsl:value-of select=”Column_C” /&gt;
        ///&lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string transformXslt {
            get {
                return ResourceManager.GetString("transformXslt", resourceCulture);
            }
        }
    }
}
